### ISSUE TITLE
Enable tick status not saved

### ISSUE THREAD

**Issue by Pablohn26** [HCAWN/gcal-multical-event-merge#11]
When I want to disable the use of the extension using the `enable` option, the status is not saved. 

![Peek 2022-08-25 12-09](https://user-images.githubusercontent.com/1228418/186637791-fd228859-1abe-4e53-9233-3ab3b8a3e7e1.gif)

**Comment by HCAWN** [comment]
@Pablohn26 I did some renaming and missed something fixed now, will be part of next version when I fix other issues 
https://github.com/HCAWN/gcal-multical-event-merge/pull/12

I also spotted your dropdown being undefined and have fixed that for new users.
