### ISSUE TITLE
Scale links when merged event does not occupy full row

### ISSUE THREAD

**Issue by michaelblyons** [HCAWN/gcal-multical-event-merge#20]
When there are multiple concurrent events, the link placement for each part of merged events doesn't seem to be in the right place. In the screenshot below, I clicked in the red circle expecting to bring up the _blue_ event of the merged set. Instead, I got the brown one.

![Calendar Screen Shot](https://user-images.githubusercontent.com/2701605/232085237-3106c146-30c4-42ec-bf6a-ce2b3c4c1dc3.png)

I suspect what is happening is that I'm clicking in a place that _would be brown_ if the merged event covered the whole width, but the scaling for links isn't accounting for the reduced width.

**Comment by HCAWN** [comment]
Fixed and under review from Google:
https://github.com/HCAWN/gcal-multical-event-merge/pull/22
Check for V2.3.4 (top left of the extension window) in a few hours/ a day
