### ISSUE TITLE
[Merging Busy events with same event at the same time]

### ISSUE THREAD

**Issue by FarhanJamil0001** [HCAWN/gcal-multical-event-merge#23]
**Describe the bug**
For some work calendars, events show as busy when connecting. It would be great to have the option to merge events at the same time and labeled Busy into one, with the name being the other name, not "Busy".

**To Reproduce**
Create a work calendar that doesn't allow you to share event names with other calendars. 
Import calendar to personal calendar.

**Device**
 - OS: MacOS Ventura
 - Browser: Chrome
 - Extension Version 2.3.4

**Additional context**
<img width="153" alt="Screenshot 2023-09-20 at 9 44 18 AM" src="https://github.com/HCAWN/gcal-multical-event-merge/assets/32781195/4e56c094-452f-4a39-a420-eb37e4715c0f">

**Comment by HCAWN** [comment]
https://github.com/HCAWN/gcal-multical-event-merge/pull/24 in review now

**Comment by HCAWN** [comment]
Live in v.2.3.5
