### ISSUE TITLE
[BUG] Event titles with unmatched ')' cause regex syntax error -> No merged formatting applied

### ISSUE THREAD

**Issue by teleksterling** [HCAWN/gcal-multical-event-merge#28]
**Describe the bug**
Event titles aren't (properly) escaped, which leads to failures during regex event matching.

This error appears in the log upon page load/refresh 20-30 times within a couple seconds (perhaps once per visible event?)
```
events.user.js:220 
Uncaught (in promise) SyntaxError: Invalid regular expression: /15_Test ), 8:30am18px/: Unmatched ')' 
    at events.user.js:220:15
    at String.match (<anonymous>)
    at findMatchingString (events.user.js:220:15)
    at events.user.js:242:57
    at Array.forEach (<anonymous>)
    at events.user.js:235:12
    at NodeList.forEach (<anonymous>)
    at merge (events.user.js:233:8)
```

**To Reproduce**
1. Create an event with a title containing a ')', without preceding '(', e.g. "Test me)".
2. Reload page. All events that should be merged, aren't.
3. Toggling off the calendar containing the offending event will restore correct formatting for remaining visible calendar items.
4. Screenshots of how it looks with extension **enabled**,  **enabled with triggering event title**  and  **disabled with triggering event title**

![Chrome extension bug report](https://github.com/HCAWN/gcal-multical-event-merge/assets/1211967/8e177e77-4fe6-4c05-b6c4-80cddfab4a85)

**Expected behaviour**
1. Code should be modified to prevent event text being interpreted as regex syntax.
2. Visible result should be that screenshot # 2 has merged formatting applied like # 1.

**Device**
 - OS: Windows 11
 - Browser: Tested on Chrome 123.0.6312.106 and Vivaldi 6.6.3271.55
 - Extension Version 2.3.6

**Additional context**
None.
Thanks for forking and improving the extension!

**Comment by HCAWN** [comment]
@teleksterling 
https://github.com/HCAWN/gcal-multical-event-merge/pull/29/commits/b1a58c5f62f32f78c31b90c439defe9914a616ff
Should be fixed in extension version 2.3.7, let me know once the update propigates to your browser through Chome

H
