### ISSUE TITLE
[BUG] Extension pushes events around

### ISSUE THREAD

**Issue by KieranCodema** [HCAWN/gcal-multical-event-merge#31]
Edit: Formatted better and added the errors as additional context
**Describe the bug**
Events are "moved" when the extension is on. The more calendars active, the more "movement" is seen in events. Events move regardless of if they are merging.

**To Reproduce**
1. The extension just needs to be turned on for the bug to be seen. The calendar needs to be populated with events.

2. Screenshot of how it looks with extension _disabled_ ![image](https://github.com/user-attachments/assets/0d6aa36f-607d-4d3e-a17f-88c1e3ae26a7)

3. Screenshot of how it looks with extension _enabled_ <img width="772" alt="CalMerge_Kieran_ExtensionOn" src="https://github.com/user-attachments/assets/ba5daed6-d6ff-4263-932a-d9b6bc647dcd">

**Expected behaviour**
1. Expect calendar items to stay where they are.

**Device**
 - OS: Windows 11
 - Browser: Chrome Version 126.0.6478.127 (Official Build) (64-bit)
 - Extension Version: 2.3.7
 
 **Additional context**
List of Errors:
![image](https://github.com/user-attachments/assets/cf252600-a320-43e8-bf3a-da7bbbfe2f1d)

Uncaught (in promise) TypeError: fillOptions[fill_style] is not a function:
![image](https://github.com/user-attachments/assets/c42561c4-6549-4cab-95e2-4a34c6a26b89)

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
![image](https://github.com/user-attachments/assets/04d0a157-dff9-4860-8d1f-a54310bffaae)

Uncaught (in promise) Error: Extension context invalidated.
![image](https://github.com/user-attachments/assets/b3c41a73-f91f-40fa-8e67-3a0818b67fae)

**Comment by macintacos** [comment]
Was about to report this same thing - I thought I was going nuts until I remembered that I had this installed, disabled it, and all of my events were aligned correctly again.

**Comment by manuellazzari-cargoone** [comment]
@macintacos same, I reported the same below, closing mine since this is much better reported

**Comment by HCAWN** [comment]
Hi all,

this was an oversight in 2.3.7
I spotted it and deployed a new build but Google isn't instant so took a day for 2.3.8

Please confirm if you are on this version that the events are where they should be?

H

**Comment by manuellazzari-cargoone** [comment]
Works for me, thanks! Awesome extension!

Il Sab 20 Lug 2024, 21:22 Henry Neilson ***@***.***> ha
scritto:

**Comment by KieranCodema** [comment]
Hi @HCAWN 
Now that I'm on version 2.38, it's working perfectly. Thanks!
