### ISSUE TITLE
[BUG]Events display at wrong time current time

### ISSUE THREAD

**Issue by osheaj** [HCAWN/gcal-multical-event-merge#36]
**Describe the bug**
Calendar events are listed on calendar view(day, month, week)  at the wrong time time of day (shifted about 3 hours ahead from Eastern time my case).  The time/timezone listed in the event is still correct.  The current time (red line) shows at the correct time.  A new event also shows at the incorrect time

**To Reproduce**
1. timezone set to Eastern - New York, create an event or view day with events, view calendar and check event time versus the time of day

2. Screenshot of how it looks with extension _disabled_
<img width="428" alt="image" src="https://github.com/user-attachments/assets/0796a9b7-6c27-4814-bac0-b0a1137ddb69">

3. Screenshot of how it looks with extension _enabled_
<img width="401" alt="image" src="https://github.com/user-attachments/assets/6378e2b8-468a-45eb-84eb-b586fde60535">

**Expected behaviour**
Events show at the correct time when viewing the calendar (see screenshot with extension disabled).

**Device**
 - OS: MacOS and Windows
 - Browser: Chrome Browser
 - Extension Version 2.3.9

**Additional context**
I did not test this with another timezone besides Eastern - New York

**Comment by amyeferrer** [comment]
I'm experiencing the same issue. It seems to recur regardless of time zone.

**Comment by HCAWN** [comment]
Hi All, Looks like Google have just changed some of their code on the calendar so that a method I use to detect what type of events are moving is no longer working. I'll aim to have a fix done in the next few hours and submitted for review.

Once in review Google usually take 12-24 hours. Will post updates here

H

**Comment by HCAWN** [comment]
https://github.com/HCAWN/gcal-multical-event-merge/pull/37

Patched the issue, submitted for review, will message when update is live
H

**Comment by ChristianSino** [comment]
Thanks the original creator and the person issuing the bug. 

I will be waiting! :)

**Comment by HCAWN** [comment]
And it's live, nice and quick from Google. Please:
-refresh/reload chrome
-check the extension is v2.3.10
-check all the events are where they are meant to be
-if all sorted, a nice review would do me and the extension wonders 😀 

I'll close this issue once reports are in it's all good!

H

**Comment by osheaj** [comment]
Looking good now, everything is where it should be.  Thanks for the quick response!

**Comment by cdavie-artium** [comment]
Thank you for the quick fix!
