### ISSUE TITLE
Out of office should use "past event" style text

### ISSUE THREAD

**Issue by michaelblyons** [HCAWN/gcal-multical-event-merge#5]
Since OOO events are dimmed, they always use the grey text instead of white-with-shadow.

**Comment by HCAWN** [comment]
@michaelblyons please share a screenshot of this as I'm not sure if https://github.com/HCAWN/gcal-multical-event-merge/pull/9 address this issue or not.

**Comment by michaelblyons** [comment]
![Screen Shot 2022-08-22 at 9 49 26 AM](https://user-images.githubusercontent.com/2701605/185937031-320a9407-ba3f-4083-a0e0-41ad95596b74.png)
![Screen Shot 2022-08-22 at 9 49 07 AM](https://user-images.githubusercontent.com/2701605/185937043-8276910b-02d6-43fe-8bcf-dba83f138789.png)

Merging events makes them extremely hard to read. I think my initial bug report was unclear about which style was better.

**Comment by michaelblyons** [comment]
It is indeed on the Weekly view calendar, but those ones were not all-day events.

**Comment by HCAWN** [comment]
![image](https://user-images.githubusercontent.com/40216444/185986962-20d259aa-1c31-450c-a2d9-f01d6d114240.png)
fixed now

**Comment by HCAWN** [comment]
https://github.com/HCAWN/gcal-multical-event-merge/commit/8b9cdbcc10e8ada88d5f7b1fe0a36303df3419b6
