### ISSUE TITLE
All-day Out of Office events have problems

### ISSUE THREAD

**Issue by michaelblyons** [HCAWN/gcal-multical-event-merge#6]
It's unclear when they merge the top, and they often make a skinny full-day event that doesn't take the whole column width.

**Comment by HCAWN** [comment]
@michaelblyons I believe this PR fixes this issue, all day events use flexbox to appear side by side rather than overlaid like normal events.

**Comment by HCAWN** [comment]
https://github.com/HCAWN/gcal-multical-event-merge/commit/8b9cdbcc10e8ada88d5f7b1fe0a36303df3419b6
