### ISSUE TITLE
Blurred gradient style

### ISSUE THREAD

**Issue by michaelblyons** [HCAWN/gcal-multical-event-merge#7]
I'm having trouble finding it now, but I recall someone making a version with fuzzy edges between vertical bars. Maybe turn the check ✅ for candy cane into a drop down list?

I personally am in the candy cane camp, but it shouldn't be too hard to add an extra style.

**Comment by HCAWN** [comment]
I've seen the extension you're talking about. I might hold off on this for now in favour of other issues if they arise. I've spotted a few bugs myself and would also love to try and restack all day events if possible.

**Comment by HCAWN** [comment]
![image](https://user-images.githubusercontent.com/40216444/185997265-0d2004e1-adf4-45ff-aa04-0739e78dbf2e.png)
latest commit to https://github.com/HCAWN/gcal-multical-event-merge/pull/9

**Comment by HCAWN** [comment]
https://github.com/HCAWN/gcal-multical-event-merge/commit/8b9cdbcc10e8ada88d5f7b1fe0a36303df3419b6
